spring.application.name=dispatch
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
##what spring deserialize to json event
#spring.kafka.consumer.properties.spring.json.value.default.type=dev.mada.dispatch.message.OrderCreated

kafka.bootstrap-servers=localhost:9092

