spring.application.name=dispatch
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#what spring deserialize to json event
spring.kafka.consumer.properties.spring.json.value.default.type=dev.mada.dispatch.message.OrderCreated